export const success_stories_data = [
    {
        slug: 'ruqqaiya-5',
        title: 'A GOVERNMENT TEACHER’S STORY OF INSPIRED INNOVATION IN TRYING TIMES',
        img1: 'https://www.zindagitrust.org/img/success/COC.jpeg',
        img2: 'https://www.zindagitrust.org/img/success/COC-SEL.jpg',
        content1: 'While our new �Social and Emotional Learning� (SEL) module was focused around student well-being, we did not anticipate how it could capture the attention of our teachers as well. A conversation with one of our teachers at Khatoon-e-Pakistan (KPS) revealed how important holistic education can be in motivating educators.',
        content2: 'Ruqqaiya started teaching at KPS in 2017, after being transferred from another government mandated teaching post. She started off as an Urdu teacher for primary students, following which she also became a Section Coordinator. In addition to this she is also teaching the (SEL) module, developed as part of the Social Studies classes.',
        content3: 'When she started out, Ruqqaiya did not have much faith in the government school education system. To her, teaching there was a cut-and-dry job with minimal need for being innovative. At least until she started teaching at KPS...',
        content4: 'Things started to change when she encountered the idea of SEL classes. The SEL platform encourages students to engage with their emotions and social behaviors through art-based activities, in order to develop life-skills.',
        content5: 'When teachers were initially being trained to conduct these classes, our Social Studies Lead said she saw a spark in Ruqqaiya to learn more about SEL, she would actively engage with trainings and ask frequent questions.',
        content6: 'Despite the SEL module being shifted online, Ruqqaiya did not give up and took it upon herself to learn how to use a smartphone (provided by Zindagi Trust as a separate initiative) to gather data and share it with her students. She has even gone the extra mile to find relevant videos online, translate and then dub them into Urdu so that her students can understand them more easily in their own teacher�s voice.',
        content7: 'When we asked Ruqqaiya about this she mentioned that she had never seen a government school take on curriculum that put it on par with private schools According to Ruqqaiya this module has encouraged students to become more contemplative and genuinely focus on their internality.',
        content8: 'According to Ruqqaiya the difference between KPS and her prior experience with government schools was as apparent as �zameen aasman ka faraq (the difference between the land and the sky)�. When asked what motivated her to push herself further at KPS, she responded that despite the fact that this was harder work, KPS was her ideal school.',
        content9: 'Ruqqaiya now observes how students react to innovative methods of teaching. Based on these observations, she fine-tunes her own style of teaching.',
        content10: 'Ruqqaiya�s journey showcases the many ways that a holistic education can impact lives � through innovations in the classroom, yes, but also through a transformation in the attitude and self-belief of a teacher, a mother and a child.',
        quote1: 'Before joining KPS, I�d only been through a standard government school education and followed that up with a government teaching job. In my village, an ideal school only existed in the books we used to read. It wasn�t until KPS that I realized it could be a reality.',
        quote2: 'I saw how well students at KPS were learning through the SEL module, they were more focused and could better understand their own emotions. I wanted that for my own children, so I made videos for them too. They can speak English as well as me now and they understand and apply SEL concepts in their own lives.'
    },
    {
        slug: 'muqdas-saeed-4',
        title: 'MUQDAS SAEED : A SOCIAL AND EMOTIONAL LEARNER IN THE TIME OF COVID 19',
        img1: 'https://www.zindagitrust.org/img/success/muqdas1.jpeg',
        img2: 'https://www.zindagitrust.org/img/success/muqdas2.jpeg',
        content1: 'Studying in class 5C, Muqdas is a 13-year-old student at Khatoon e Pakistan Government Girls School (KPS). She has been studying here since the first grade. The past year or two has seen an unprecedented level of growth and learning for Muqdas, beyond the confines of academic learning. Muqdas is a high achieving student in most of her classes and a keen artist who works hard to maintain this course every day. Her career aspirations were to want to go to the army but her parents� concerns for her safety led her to resign herself to a different dream � that of becoming a doctor.',
        content2: 'Like many students in Pakistan, Muqdas believes that good grades are important and she should work hard to achieve them. When she was in the 4th grade she was elected as a Prefect, a role on the Students� Council, for her class. Muqdas has always been a high achiever, but ended up failing her Science class that year. Out of concern for her studies and the regard of her teachers Muqdas relinquished her role as prefect so that she may focus better on her studies.',
        content3: 'She said when asked for how she faces the challenges in her life, which seems to have worked well for Muqdas as she was able to regain her position as prefect in the 5th grade. She appreciates all those who help her, the teachers who are willing to work with her and supported her in this.',
        content4: 'COVID 19 presents a difficult time for someone like Muqadas who is quite passionate in her studies. Online classes make learning more difficult � even for an otherwise high-achieving student like Muqadas it is challenging to understand concepts, especially mathematics, which she considers her favorite subject. Muqadas shared that although COVID19 posed many challenges which still persist, many of her fears and concerns have been allayed through the efforts of her teachers, the Admin Officer from Zindagi Trust who coordinates between the students and the school and through the provision of a smartphone she got from the school as part of an intervention to keep students connected and learning.',
        content5: 'The smartphone particularly has connected Muqdas to the Social and Emotional Learning (SEL) classes that are being taught through online means to help children express themselves and harness their emotions in a healthy way. Muqdas has suffered from kidney disease for a long time has been often prone to fevers.',
        content6: 'The impact of the classes, Muqdas explains has caused her to think about herself more, to harness the ability to self-care in a healthy manner and caused her to adhere to her medication. This practice has led to her keeping healthy both mentally and physically. A student who was dedicated to her studies at the expense of co-curricular activities, she has now shown self reflection and self growth. This has been an essential part of learning at school in the past year despite the uncertainty that the year has presented.',
        quote1: 'Science is a difficult subject for me so I work on it daily.',
        quote2: 'SEL classes have taught me to think about myself, now I take my medication and do not get fevers frequently'
    },
    {
        slug: 'maliha-ali-3',
        title: 'ADVANCING THROUGH THE CHESSBOARD OF LIFE',
        img1: 'https://www.zindagitrust.org/img/success/maliha-1.jpg',
        content1: "Maliha is a recent graduate of SMB Fatima Jinnah Government Girls' School managed by Zindagi Trust. She started her chess journey from casual games at home but it was the chess class at her school that began to shape her life in a new direction. The quietness and the concentration that chess requires drew her towards the game and after encouragement from her school chess teacher she signed up for the Chess Club at school, designed for students who show special talent.",
        content2: 'Maliha thinks playing chess against the clock has helped expand her mental capacity to solve problems, be itdoing 3-digit multiplication in her headorbreezing throughpop quizzes to balance equations. In subjects like Physics and Chemistry, she is able to visualize the concepts being taught which she thinks helps her tackle difficult questions. She exudes a quiet humble confidence:',
        content3: 'She also credits chess as havingmade in impact on her personality. Having played in so many competitions and facing opponents from all age groups and backgrounds, including the best elite private schools of the city, has helped develop her confidence and communication skills. She says she has gone from being a shy middle school-er to a quick-witted, present-minded teenager. She is now confident not only in talking to her competitors but also in her ability to overcome any challenges that come her way.',
        content4: "Maliha has won scores of school and city level competitions in chess. She participated in the 2018 National Women's Chess Championship, an open event with no age restrictions, which meant she was up against 30 of the most formidable players from across Pakistan. After a grueling 5-day championship, with three back-to-back rounds lasting three hours every day, Maliha finished at the 7th position - a proud moment for us, specially given that she was not only the youngest player to feature in the top 10 but also the only player from a government school to feature in the final round of the competition.Earlier that year, she was also invited to play chess with Pakistan's Chief of Army Staff, General Qamar Javed Bajwa, a challenge she enjoyed and excelled in!",
        content5: "Taking note of the impact chess can have on a child's problem-solving skills and overall brain development, Zindagi Trust started teaching chess at its adopted government schools in 2011. In the summer of 2019, the Mind Sports Association of Pakistan took the trust's chess program to TCF schools - a great achievement for us and a welcome sign that students across a large network of schools will now benefit from the advantages of playing chess. Having graduated the same summer, Maliha was selected to coach the teachers at TCF on how to teach chess, a remarkable achievement for her and a source of great pride for us.",
        content6: 'Now in her first year of college, Maliha aspires to be a doctor. Her inspiration comes from her chess coach at school, international chess master and former national champion Shehzad Mirza, who taught her how to balance her professional career and her passion for chess. She leaves us with this goal: to represent Pakistan in chess competitions internationally and win!',
        quote1: `You have to calculate ahead for your next two moves and your opponent's.When I first got into this I thought wow, this is tough...but it was exactly that which also made it fun for me. I took it as a challenge."`,
        quote2: `There's nothing special about me or the other girls on the team. It's just that playing chess has trained our minds to solve quickly and given us the self-belief that we can work through any challenge - on the chessboard or on an exam paper."`
    },
    {
        slug: 'rabiya-abbasi-2',
        title: 'RABIYA - ON THE FAST TRACK TO ACHIEVING BIG DREAMS',
        img1: 'https://www.zindagitrust.org/img/success/rabiya-1.jpg',
        img2: 'https://www.zindagitrust.org/img/success/rabiya-2.jpg',
        content1: 'Rabiya joined Khatoon-e-Pakistan Government Girls School three years ago in the Fast Track stream where teachers focus on the core subjects of language, math and science to bring students up to speed with their grade-level learning expectations. This is a program designed for students who have had a gap in their schooling and are struggling to keep pace with others in their age group.',
        content2: "Over the past three years, she has flourished at the school: not only has she been able to make the transition from Fast Track to the regular grades successfully, she has excelled in both her academic and co-curricular performance. This successful transition has led her teachers to select her on the Students' Council as a House Captain. This is doubly impressive when you consider the multiple levels at which Rabiya had to adapt - moving from a small town in the north of Pakistan to the megacity down south, adjusting to the change in her family situation.",
        content3: 'Rabiya, now 13, has demonstrated a go-getter attitude from a young age and has done her best to grab every opportunity that the school has offered for her holistic development. In her academic classes, she enjoys the freedom to ask many questions and dig deeper into a topic she wants to understand better. This has helped her get comfortable with Sindhi, the local language that she struggled with in her last school in Karachi and has also led her to enjoy her Maths class.',
        content4: 'Beyond academics, she has explored every sport taught in the school - taekwondo, futsal, hockey, badminton, but her favourite is cricket. Her teachers are happy with her academic progress and support her pursuit of sports and art. She is on several school sports teams and has become confident from playing matches against other schools. She wants to continue exploring new fields introduced by the school.',
        content5: 'In addition to doing well in her classes and co-curricular activities, she has also developed strong goals for the future - she wants to grow up to become a national cricketer and a Deputy Commissioner. Her career goals are partly inspired by a character in a local television show raised by a single mother who studied and worked hard alongside privileged compatriots to enter the Pakistan Civil Service and eventually became the leading bureaucrat heading an administrative division.',
        quote1: 'Abbudecided to quit his teaching job in Murree and move to Karachi with me and my 8 siblings to work as a rickshaw driver. I was studying in a nearby school which was made in a small house - there was no space to run around or play.',
        quote2: 'Here I am on the taekwondo and badminton and cricket and futsal teams and I have had the chance to compete against other schools! I now love Maths! I get to participate in everything I like, from art and drama to sports and science clubs. I love this school and never want to leave - I hope it becomes a university by the time I finish high school!',
        quote3: 'I want to progress towards success through my own hard work like she did.'
    },
    {
        slug: 'bushra-maqsood-1',
        title: 'BUSHRA MAQSOOD - REPRESENTED PAKISTAN AT THE SEEDS OF PEACE CAMP IN MAINE, USA, SELECTED FROM OVER 300 APPLICANTS',
        video: 'Lyue33jnfkg'
    }
]

export default success_stories_data